### ISSUE TITLE
Index Task problem

### ISSUE THREAD

**Issue by bastiao** [bioinformatics-ua/dicoogle#121]
Sounds like a dependency problem. (it says dicoogle-1.0-SNAPSHOT). Probably is it included in a plugin "jar with dependencies". 

```

java.util.concurrent.CancellationException
        at java.util.concurrent.FutureTask.report(FutureTask.java:121) ~[?:1.8.0_45]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_45]
        at pt.ua.dicoogle.taskManager.RunningIndexTasks.toJson(RunningIndexTasks.java:108) ~[dicoogle.jar:1.0-SNAPSHOT]
        at pt.ua.dicoogle.server.web.servlets.management.RunningTasksServlet.doGet(RunningTasksServlet.java:44) ~[dicoogle.jar:1.0-SNAPSHOT]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:735) ~[dicoogle.jar:1.0-SNAPSHOT]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[dicoogle.jar:1.0-SNAPSHOT]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:681) ~[dicoogle.jar:1.0-SNAPSHOT]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1452) ~[dicoogle.jar:1.0-SNAPSHOT]
        at pt.ua.dicoogle.server.web.CORSFilter.doFilter(CORSFilter.java:76) ~[dicoogle.jar:1.0-SNAPSHOT]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1423) ~[dicoogle.jar:1.0-SNAPSHOT]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:450) [dicoogle.jar:1.0-SNAPSHOT]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:211) [dicoogle.jar:1.0-SNAPSHOT]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1083) [dicoogle.jar:1.0-SNAPSHOT]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:379) [dicoogle.jar:1.0-SNAPSHOT]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175) [dicoogle.jar:1.0-SNAPSHOT]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1017) [dicoogle.jar:1.0-SNAPSHOT]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136) [dicoogle.jar:1.0-SNAPSHOT]
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:258) [dicoogle.jar:1.0-SNAPSHOT]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [dicoogle.jar:1.0-SNAPSHOT]
        at org.eclipse.jetty.server.Server.handle(Server.java:445) [dicoogle.jar:1.0-SNAPSHOT]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:260) [dicoogle.jar:1.0-SNAPSHOT]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:225) [dicoogle.jar:1.0-SNAPSHOT]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358) [dicoogle.jar:1.0-SNAPSHOT]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596) [dicoogle.jar:1.0-SNAPSHOT]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527) [dicoogle.jar:1.0-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
WARN  servlet.ServletHandler (ServletHandler.java:504) - /index/task
java.util.concurrent.CancellationException
        at java.util.concurrent.FutureTask.report(FutureTask.java:121) ~[?:1.8.0_45]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_45]
        at pt.ua.dicoogle.taskManager.RunningIndexTasks.toJson(RunningIndexTasks.java:108) ~[


```

**Comment by Enet4** [comment]
What plugins were installed when that happened?

**Comment by bastiao** [comment]
cbir-1.0-SNAPSHOT-jar-with-dependencies.jar
filestorage-2.0.0-jar-with-dependencies.jar
lucene-2.0.0.jar
multimodal-0.5.2-ALPHA-jar-with-dependencies.jar

**Comment by Enet4** [comment]
The strangest part of your dump is that "dicoogle.jar:1.0-SNAPSHOT" is mentioned. That can only make sense if you were running v1.0-SNAPSHOT of Dicoogle itself.

Nevertheless, it seems to be the same issue as #127 with a different diagnosis.
