### ISSUE TITLE
Unindex patient with studies with many files

### ISSUE THREAD

**Issue by bastiao** [bioinformatics-ua/dicoogle#142]
```
INFO  net.Association (Association.java:990) - XMPPDICOM(138) >> A-RELEASE-RQ
INFO  net.PDUEncoder (PDUEncoder.java:120) - XMPPDICOM(138) << A-RELEASE-RP
INFO  net.Association (Association.java:915) - XMPPDICOM(138): close Socket[addr=/172.17.0.234,port=35601,localport=1045]
INFO  lucene.LuceneQuery (LuceneQuery.java:144) - Finished opening result stream, Query: 0,1,*:*
WARN  servlet.ServletHandler (ServletHandler.java:504) - /management/tasks/remove
java.lang.IllegalStateException: Form too large 419847>200000
    at org.eclipse.jetty.server.Request.extractParameters(Request.java:336) ~[dicoogle.jar:1.0-SNAPSHOT]
    at org.eclipse.jetty.server.Request.getParameterValues(Request.java:802) ~[dicoogle.jar:1.0-SNAPSHOT]
    at pt.ua.dicoogle.server.web.servlets.management.RemoveServlet.doPost(RemoveServlet.java:53) ~[dicoogle.jar:1.0-SNAPSHOT]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:755) ~[dicoogle.jar:1.0-SNAPSHOT]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[dicoogle.jar:1.0-SNAPSHOT]
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:681) ~[dicoogle.jar:1.0-SNAPSHOT]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1452) ~[dicoogle.jar:1.0-SNAPSHOT]
    at pt.ua.dicoogle.server.web.CORSFilter.doFilter(CORSFilter.java:76) ~[dicoogle.jar:1.0-SNAPSHOT]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1423) ~[dicoogle.jar:1.0-SNAPSHOT]
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:450) [dicoogle.jar:1.0-SNAPSHOT]
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:211) [dicoogle.jar:1.0-SNAPSHOT]
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1083) [dicoogle.jar:1.0-SNAPSHOT]
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:379) [dicoogle.jar:1.0-SNAPSHOT]
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175) [dicoogle.jar:1.0-SNAPSHOT]
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1017) [dicoogle.jar:1.0-SNAPSHOT]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136) [dicoogle.jar:1.0-SNAPSHOT]
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:258) [dicoogle.jar:1.0-SNAPSHOT]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [dicoogle.jar:1.0-SNAPSHOT]
    at org.eclipse.jetty.server.Server.handle(Server.java:445) [dicoogle.jar:1.0-SNAPSHOT]
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:260) [dicoogle.jar:1.0-SNAPSHOT]
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:225) [dicoogle.jar:1.0-SNAPSHOT]
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358) [dicoogle.jar:1.0-SNAPSHOT]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596) [dicoogle.jar:1.0-SNAPSHOT]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527) [dicoogle.jar:1.0-SNAPSHOT]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
WARN  servlet.ServletHandler (ServletHandler.java:504) - /management/tasks/unindex
```

Reported from BMD Software.

**Comment by packj** [comment]
This seems like a pretty significant bug.

**Comment by bastiao** [comment]
This is fixed already.
See b45fe6f75a945ca251dbc26918163cde87189fb3
