### ISSUE TITLE
Can't login due to java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder

### ISSUE THREAD

**Issue by Ebeid** [bioinformatics-ua/dicoogle#368]
Hi All,

I followed instructions here https://bioinformatics-ua.github.io/dicoogle-learning-pack/docs/setup/ and when I tried to login and I get the below error. Could you please help ?
------------------------------------------------------------------------------------------------------
➜  DicoogleDir java -jar dicoogle.jar -s

INFO  plugins.PluginController (PluginController.java:88) - Creating PluginController Instance
INFO  lucene.LucenePluginSet (LucenePluginSet.java:45) - Loading lucene plugin set
INFO  lucene.LuceneIndexer (LuceneIndexer.java:132) - Created Lucene Indexer Plugin
INFO  plugins.PluginController (PluginController.java:116) - Loaded Local Plugins
INFO  plugins.PluginController (PluginController.java:127) - Loading plugin: file-storage
INFO  plugins.PluginController (PluginController.java:127) - Loading plugin: luceneset
INFO  plugins.PluginController (PluginController.java:148) - Settings pushed to plugins
INFO  plugins.PluginController (PluginController.java:150) - Settings pushed to web UI plugins
INFO  plugins.PluginController (PluginController.java:153) - Added default storage plugin
INFO  plugins.PluginController (PluginController.java:219) - Initializing plugin rest interfaces
INFO  plugins.PluginController (PluginController.java:233) - Finished initializing rest interfaces
INFO  plugins.PluginController (PluginController.java:237) - Initializing jetty interface
INFO  server.ControlServices (ControlServices.java:242) - Starting WebServer
INFO  web.DicoogleWeb (DicoogleWeb.java:122) - Starting Web Services in DicoogleWeb. Port: 8080
INFO  server.ControlServices (ControlServices.java:249) - Starting Dicoogle Web
INFO  plugins.PluginController (PluginController.java:160) - Initialized plugins
ERROR users.RolesXML (RolesXML.java:137) - roles.xml (No such file or directory)
java.io.FileNotFoundException: roles.xml (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method) ~[?:?]
	at java.base/java.io.FileInputStream.open(FileInputStream.java:220) ~[?:?]
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:158) ~[?:?]
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:113) ~[?:?]
	at pt.ua.dicoogle.server.users.RolesXML.getXML(RolesXML.java:108) [dicoogle.jar:2.5.0]
	at pt.ua.dicoogle.server.web.auth.Authentication.<init>(Authentication.java:43) [dicoogle.jar:2.5.0]
	at pt.ua.dicoogle.server.web.auth.Authentication.getInstance(Authentication.java:60) [dicoogle.jar:2.5.0]
	at pt.ua.dicoogle.server.web.auth.Session.getSuccessfulLogin(Session.java:56) [dicoogle.jar:2.5.0]
	at pt.ua.dicoogle.server.web.auth.Session.webappLogin(Session.java:246) [dicoogle.jar:2.5.0]
	at pt.ua.dicoogle.server.web.servlets.accounts.LoginServlet.doPost(LoginServlet.java:49) [dicoogle.jar:2.5.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755) [dicoogle.jar:2.5.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [dicoogle.jar:2.5.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:681) [dicoogle.jar:2.5.0]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1452) [dicoogle.jar:2.5.0]
	at pt.ua.dicoogle.server.web.CORSFilter.doFilter(CORSFilter.java:91) [dicoogle.jar:2.5.0]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1423) [dicoogle.jar:2.5.0]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:450) [dicoogle.jar:2.5.0]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:211) [dicoogle.jar:2.5.0]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1083) [dicoogle.jar:2.5.0]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:379) [dicoogle.jar:2.5.0]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175) [dicoogle.jar:2.5.0]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1017) [dicoogle.jar:2.5.0]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136) [dicoogle.jar:2.5.0]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:258) [dicoogle.jar:2.5.0]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [dicoogle.jar:2.5.0]
	at org.eclipse.jetty.server.Server.handle(Server.java:445) [dicoogle.jar:2.5.0]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:260) [dicoogle.jar:2.5.0]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:225) [dicoogle.jar:2.5.0]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358) [dicoogle.jar:2.5.0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596) [dicoogle.jar:2.5.0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527) [dicoogle.jar:2.5.0]
	at java.base/java.lang.Thread.run(Thread.java:844) [?:?]
INFO  users.UserFileHandle (UserFileHandle.java:148) - No such users file "users.xml", will create one with default settings.
WARN  servlet.ServletHandler (ServletHandler.java:540) - Error for /login
java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder
	at pt.ua.dicoogle.server.users.HashService.getSHA1Hash(HashService.java:48) ~[dicoogle.jar:2.5.0]
	at pt.ua.dicoogle.server.users.UsersStruct.setDefaults(UsersStruct.java:68) ~[dicoogle.jar:2.5.0]
	at pt.ua.dicoogle.server.users.UsersXML.getXML(UsersXML.java:144) ~[dicoogle.jar:2.5.0]
	at pt.ua.dicoogle.server.web.auth.Authentication.<init>(Authentication.java:46) ~[dicoogle.jar:2.5.0]
	at pt.ua.dicoogle.server.web.auth.Authentication.getInstance(Authentication.java:60) ~[dicoogle.jar:2.5.0]
	at pt.ua.dicoogle.server.web.auth.Session.getSuccessfulLogin(Session.java:56) ~[dicoogle.jar:2.5.0]
	at pt.ua.dicoogle.server.web.auth.Session.webappLogin(Session.java:246) ~[dicoogle.jar:2.5.0]
	at pt.ua.dicoogle.server.web.servlets.accounts.LoginServlet.doPost(LoginServlet.java:49) ~[dicoogle.jar:2.5.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755) ~[dicoogle.jar:2.5.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[dicoogle.jar:2.5.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:681) ~[dicoogle.jar:2.5.0]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1452) ~[dicoogle.jar:2.5.0]
	at pt.ua.dicoogle.server.web.CORSFilter.doFilter(CORSFilter.java:91) ~[dicoogle.jar:2.5.0]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1423) ~[dicoogle.jar:2.5.0]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:450) [dicoogle.jar:2.5.0]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:211) [dicoogle.jar:2.5.0]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1083) [dicoogle.jar:2.5.0]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:379) [dicoogle.jar:2.5.0]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175) [dicoogle.jar:2.5.0]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1017) [dicoogle.jar:2.5.0]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136) [dicoogle.jar:2.5.0]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:258) [dicoogle.jar:2.5.0]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [dicoogle.jar:2.5.0]
	at org.eclipse.jetty.server.Server.handle(Server.java:445) [dicoogle.jar:2.5.0]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:260) [dicoogle.jar:2.5.0]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:225) [dicoogle.jar:2.5.0]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358) [dicoogle.jar:2.5.0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596) [dicoogle.jar:2.5.0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527) [dicoogle.jar:2.5.0]
	at java.base/java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582) ~[?:?]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499) ~[?:?]
	... 30 more

**Comment by Enet4** [comment]
My hunch was right. One of the implementation details in 2.5.0 is relying on an internal API, which is no longer available from Java 9 onwards. I have requested to push the changes to our master branch as well (#369), so that it can be included in a future v2 patch release. In the mean time, you can either (1) build the fixed version of Dicoogle by following the instructions [here](https://bioinformatics-ua.github.io/dicoogle-learning-pack/docs/building/) on branch [`bug/v2_base64_internal_api`](https://github.com/bioinformatics-ua/dicoogle/tree/bug/v2_base64_internal_api), or (2) run Dicoogle with Java 8 instead.

**Comment by Enet4** [comment]
Just another note, the "missing roles.xml" warning is another unrelated issue, #265. It is already fixed upstream, and should not affect general usage of Dicoogle. Still, you can make the warning disappear by creating a new "roles.xml" file yourself at your working directory:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Roles/>
```

**Comment by bastiao** [comment]
@Ebeid thanks for reporting. We will keep version 2 with support for Java 8. All issues related with Java > 8 will come at version 3. 
@Enet4 That patch (https://github.com/bioinformatics-ua/dicoogle/pull/369) could be applied in version 2, indeed. However, I don't know if any other parts of the code could break with Java > 8, so it's safer to keep that support only at version 3 and release a RC/Alpha soon, so we can make it trial for all end-users.
