### ISSUE TITLE
Failed gulp-sass script

### ISSUE THREAD

**Issue by NEONKID** [bioinformatics-ua/dicoogle#383]
Greetings. I did a build with Maven to use the released version 2.5 of Dicoogle. However, I get the following error message:

```bash
25397 verbose stack Error: node-sass@3.13.1 install: `node scripts/install.js`
25397 verbose stack Exit status 1
25397 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
25397 verbose stack     at emitTwo (events.js:126:13)
25397 verbose stack     at EventEmitter.emit (events.js:214:7)
25397 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
25397 verbose stack     at emitTwo (events.js:126:13)
25397 verbose stack     at ChildProcess.emit (events.js:214:7)
25397 verbose stack     at maybeClose (internal/child_process.js:915:16)
25397 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
25398 verbose pkgid node-sass@3.13.1
25399 verbose cwd /home/neonkid/dicoogle/dicoogle/src/main/resources/webapp
25400 verbose Linux 4.15.0-47-generic
25401 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
25402 verbose node v8.15.0
25403 verbose npm  v6.4.1
25404 error code ELIFECYCLE
25405 error errno 1
25406 error node-sass@3.13.1 install: `node scripts/install.js`
25406 error Exit status 1
25407 error Failed at the node-sass@3.13.1 install script.
25407 error This is probably not a problem with npm. There is likely additional logging output above.
25408 verbose exit [ 1, true ]
```

**Comment by Enet4** [comment]
I'm afraid that I could not reproduce this. Additional details would be appreciated in order to understand the problem:

- Are you building the program with `mvn install` at the project's root?
- Was this attempted on the `dev` branch?
- Can you provide the full build log? That snippet alone might not be enough.

**Comment by NEONKID** [comment]
```
[INFO] --- frontend-maven-plugin:1.7.6:npm (npm install) @ dicoogle ---
[INFO] Running 'npm install' in /home/ubuntu/dicoogle/dicoogle/src/main/resources/webapp
[WARNING] npm WARN deprecated core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
[WARNING] npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
[WARNING] npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-prese-env now: please read babeljs.io/env to update!
[ERROR] npm ERR! Linux 4.15.0-47-generic
[ERROR] npm ERR! argv "/home/ubuntu/dicoogle/dicoogle/target/node/node" "/home/ubuntu/dicoogle/dicoogle/target/node/node_modules/npm/bin/npm-cli.js" "install"
[ERROR] npm ERR! node v6.9.1
[ERROR] npm ERR! npm  v3.10.10
[ERROR] npm ERR! code EREADFILE
[ERROR]
[ERROR] npm ERR! Error extracting /home/ubuntu/.npm/node-sass/4.12.0/package.tgz archive: EACCES: permission denied, open '/home/ubuntu/.npm/node-sass/4.12.0/package.tgz'
[ERROR] npm ERR!
[ERROR] npm ERR! If you need help, you may report this error at:
[ERROR] npm ERR!     <https://github.com/npm/npm/issues>
[ERROR]
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     /home/ubuntu/dicoogle/dicoogle/src/main/resources/webapp/npm-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] dicoogle-all ....................................... SUCCESS [  0.532 s]
[INFO] dicoogle-sdk ....................................... SUCCESS [  1.702 s]
[INFO] dicoogle-sdk-ext ................................... SUCCESS [  0.729 s]
[INFO] dicoogle ........................................... FAILURE [01:27 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:31 min
[INFO] Finished at: 2019-05-09T21:32:51+09:00
[INFO] Final Memory: 37M/2308M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.7.6:npm (npm install) on project dicoogle: Failed to run task: 'npm install' failed. org.apache.commons.exec.ExecuteException: Process exited with an error:1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :dicoogle
```
I did the build from the root of the project. ```dev``` branch, and ```2.5.0``` release branch.

**Comment by Enet4** [comment]
While we cannot entirely pinpoint the reason why this happened from here, the good news is that the upstream version of Dicoogle 3 no longer uses `node-sass` since #436, making the former issue no longer applicable.

For Dicoogle 2, one will have to either stick with using `mvn` at the project root without attempting to build the web app manually, or following the given recommended Node.js+npm versions according to that version. Still, we would recommend new installations to use Dicoogle 3.
