### ISSUE TITLE
Issues While Uploading Dicom File in DICOOGLE Server

### ISSUE THREAD

**Issue by SuketuS** [bioinformatics-ua/dicoogle#455]
Hello Team,

I have noticed one issues as below can any one guide on me how can this be solved

INFO  net.Association (Association.java:148) - Association(4) accepted Socket[addr=/xxxxxxxxxxxxx,port=xxxxxxx,localport=xxxxxx]
INFO  net.Association (Association.java:964) - Association(4): A-ASSOCIATE-RQ Android >> PERSONALSTORAGE
INFO  net.PDUEncoder (PDUEncoder.java:156) - Android(4): A-ASSOCIATE-AC PERSONALSTORAGE << Android
INFO  net.PDUDecoder (PDUDecoder.java:515) - Android(4) >> 1:C-STORE-RQ[pcid=3, prior=0
        cuid=1.2.840.10008.5.1.4.1.1.6.1/Ultrasound Image Storage
        iuid=1.2.276.0.7230010.3.1.4.16777343.2066.1616581927.805196
        ts=1.2.840.10008.1.2.4.50/JPEG Baseline (Process 1)]
INFO  net.Association (Association.java:916) - Android(4): close Socket[addr=/xxxxxxxxxxxxx,port=xxxxxxx,localport=xxxxxx]
java.lang.NullPointerException
        at pt.ua.ieeta.filestorageplugin.utils.DicomUtils.getDirectory(DicomUtils.java:72)
        at pt.ua.ieeta.filestorageplugin.utils.DicomUtils.getPath(DicomUtils.java:99)
        at pt.ua.ieeta.filestorageplugin.FileStoragePlugin.store(FileStoragePlugin.java:143)
        at pt.ua.dicoogle.server.DicomStorage.onCStoreRQ(DicomStorage.java:278)
        at pt.ua.dicoogle.server.DicomStorage.cstore(DicomStorage.java:252)
        at org.dcm4che2.net.DicomServiceRegistry.process(DicomServiceRegistry.java:238)
        at org.dcm4che2.net.NetworkApplicationEntity.perform(NetworkApplicationEntity.java:1185)
        at org.dcm4che2.net.Association.onDimseRQ(Association.java:1010)
        at org.dcm4che2.net.PDUDecoder.decodeDIMSE(PDUDecoder.java:530)
        at org.dcm4che2.net.Association.onPDataTF(Association.java:987)
        at org.dcm4che2.net.State$Sta6.receivedPDataTF(State.java:239)
        at org.dcm4che2.net.Association.receivedPDataTF(Association.java:983)
        at org.dcm4che2.net.PDUDecoder.nextPDU(PDUDecoder.java:231)
        at org.dcm4che2.net.Association.run(Association.java:882)
        at java.lang.Thread.run(Thread.java:748)

Verification to dicom server was successful

**Comment by SuketuS** [comment]
Updated ts=1.2.840.10008.1.2.4.50 in server.xml but still we were facing the issue

**Comment by Enet4** [comment]
Thank you for reporting. I strongly suspect that the file that was being uploaded may be missing some attributes required for the file storage implementation (a custom constraint which allows it to create a path of directories). The free file storage plugin (provided with the downloaded bundle) requires the either the _AccessionNumber_ or the _PatientName_ DICOM attributes to be present in the file.

Please see if it helps to ensure that an accession number or patient name are provided (can be just stub values). If it does not, you might need to reach out to [BMD Software](https://www.bmd-software.com) for professional assistance.

**Comment by SuketuS** [comment]
Seems to be Working fine
