### ISSUE TITLE
ERROR in Indexing Task

### ISSUE THREAD

**Issue by Kesling515** [bioinformatics-ua/dicoogle#469]
I am trying to use c-store service, and I used dcm4che toolkit to run command "dcmsnd DICOOGLE-STORAGE@127.0.0.1:6666 C:\XXX. The dicom files store in my specified directory successfully, but Index fail.
And this error in the console:

ERROR lucene.LuceneIndexer$2 (LuceneIndexer.java:224) - ERROR in Indexing Task
java.lang.IllegalArgumentException: Directory MMapDirectory@D:\XXX\dicoogle\index\indexed lockFactory=org.apache.lucene.store.NativeFSLockFactory@4bc4f6b1 still has pending deleted files; cannot initialize IndexWriter
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:789) ~[lucene-3.0.1.jar:?]
	at dicoogle.lucene.LuceneIndexer.beginTransaction(LuceneIndexer.java:253) ~[lucene-3.0.1.jar:?]
	at dicoogle.lucene.LuceneIndexer.access$100(LuceneIndexer.java:71) ~[lucene-3.0.1.jar:?]
	at dicoogle.lucene.LuceneIndexer$2.call(LuceneIndexer.java:203) [lucene-3.0.1.jar:?]
	at dicoogle.lucene.LuceneIndexer$2.call(LuceneIndexer.java:189) [lucene-3.0.1.jar:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_291]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_291]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_291]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_291]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_291]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_291]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_291]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_291]
INFO  lucene.LuceneIndexer$2 (LuceneIndexer.java:229) - Finished Index Task: 1589912486,IndexReport [nIndexedFiles=0, nErrors=1, elapsedTime=8]

**Comment by Peng-Da** [comment]
I met same problem.Have you resolved it ?

**Comment by Enet4** [comment]
This is not a problem with the core Dicoogle project, but with the open Lucene-based plugin, which is not hosted in this repository.

With that said, @Peng-Da If you can provide more details about this issue and a list of steps to reproduce it, this may help the Dicoogle team fix it in future versions.

**Comment by Peng-Da** [comment]
@Enet4 
I use dicoogle 3.0.6 and dicoogle plugins(lucene and filestorage) . Got error logs below:

`2022-05-06 18:01:07 | DEBUG [pool-32-thread-1] (FileStoragePlugin.java:149) - Trying to store file to FS path C:\Users\Admini\AppData\Local\Temp\RuiPengPetHospital\US\2022\05\06\doghuniu\1.2.840.113619.2.400.385732288.1651859801.18.1.64.dcm
2022-05-06 18:01:07 | DEBUG [pool-32-thread-1] (FileStoragePlugin.java:159) - Assigning new file to URI file:///C:/Users/Admini/AppData/Local/Temp/RuiPengPetHospital/US/2022/05/06/doghuniu/1.2.840.113619.2.400.385732288.1651859801.18.1.64.dcm
2022-05-06 18:01:07 | INFO  [Thread-6] (PluginController.java:661) - Starting Indexing procedure for file:///C:/Users/Admini/AppData/Local/Temp/RuiPengPetHospital/US/2022/05/06/doghuniu/1.2.840.113619.2.400.385732288.1651859801.18.1.64.dcm
2022-05-06 18:01:07 | DEBUG [Thread-6] (PluginController.java:416) - Retrieved storage for scheme: file:///C:/Users/Admini/AppData/Local/Temp/RuiPengPetHospital/US/2022/05/06/doghuniu/1.2.840.113619.2.400.385732288.1651859801.18.1.64.dcm
2022-05-06 18:01:07 | DEBUG [Thread-6] (FileStoragePlugin.java:241) - FileStorage.at("file:///C:/Users/Admini/AppData/Local/Temp/RuiPengPetHospital/US/2022/05/06/doghuniu/1.2.840.113619.2.400.385732288.1651859801.18.1.64.dcm")
2022-05-06 18:01:07 | INFO  [Thread-6] (PluginController.java:694) - Finished firing all indexing plugins for file:///C:/Users/Admini/AppData/Local/Temp/RuiPengPetHospital/US/2022/05/06/doghuniu/1.2.840.113619.2.400.385732288.1651859801.18.1.64.dcm
2022-05-06 18:01:07 | DEBUG [pool-2-thread-4] (LuceneIndexer.java:195) - Started Index Task: 662927524
2022-05-06 18:01:07 | ERROR [pool-2-thread-4] (LuceneIndexer.java:224) - ERROR in Indexing Task
java.lang.IllegalArgumentException: Directory MMapDirectory@E:\projects\pacs-client\index\indexed lockFactory=org.apache.lucene.store.NativeFSLockFactory@79494cd4 still has pending deleted files; cannot initialize IndexWriter
        at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:789) ~[lucene-3.0.0.jar:?]
        at dicoogle.lucene.LuceneIndexer.beginTransaction(LuceneIndexer.java:253) ~[lucene-3.0.0.jar:?]
        at dicoogle.lucene.LuceneIndexer.access$100(LuceneIndexer.java:71) ~[lucene-3.0.0.jar:?]
        at dicoogle.lucene.LuceneIndexer$2.call(LuceneIndexer.java:203) [lucene-3.0.0.jar:?]
        at dicoogle.lucene.LuceneIndexer$2.call(LuceneIndexer.java:189) [lucene-3.0.0.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_322]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_322]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_322]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_322]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_322]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_322]
2022-05-06 18:01:07 | INFO  [pool-2-thread-4] (LuceneIndexer.java:229) - Finished Index Task: 662927524,IndexReport [nIndexedFiles=0, nErrors=1, elapsedTime=5]
2022-05-06 18:01:07 | INFO  [pool-2-thread-4] (PluginController.java:683) - Task [c5b1aa46-6d06-42b0-a3a3-6362d3c41ce5] complete: file:///C:/Users/Admini/AppData/Local/Temp/RuiPengPetHospital/US/2022/05/06/doghuniu/1.2.840.113619.2.400.385732288.1651859801.18.1.64.dcm is indexed
`

It happened sometimes,not always.
thanks

**Comment by Enet4** [comment]
@Peng-Da The stack trace appears to suggest that an older version of the Lucene plugin itself is in use. Can you try again using the latest combination of Dicoogle and its _filestorage_ + _lucene_ plugins (3.0.7)?

In addition, can you check whether adding the option `-Ddicoogle.index.async=false` helps to mitigate the problem?

**Comment by logicorptech** [comment]
Hi ..@Enet4 i have got same issue, can you help to resolve it, i didn't find -Ddicoogle.index.async=false option in settings

**Comment by Enet4** [comment]
Please consider trying again with the latest version of Dicoogle, 3.4.1. If the issue persists, consider filing the issue again over at [dicoogle-plugins](https://github.com/dicoogle/dicoogle-plugins/), as this pertains to the lucene indexer plugin.
