### ISSUE TITLE
IO exception when sending videos from Ultrasound

### ISSUE THREAD

**Issue by beavermml** [bioinformatics-ua/dicoogle#685]
2024-02-29 07:16:07 | WARN  [DicoogleStorage-12] (Association.java:893) - i/o exception in State Sta6
java.io.EOFException: null
        at org.dcm4che2.net.PDUDecoder.readFully(PDUDecoder.java:103) ~[dicoogle.jar:3.3.5]
        at org.dcm4che2.net.PDUDecoder.nextPDU(PDUDecoder.java:155) ~[dicoogle.jar:3.3.5]
        at org.dcm4che2.net.Association.run(Association.java:882) ~[dicoogle.jar:3.3.5]
        at pt.ua.dicoogle.server.LoggingExecutor.lambda$execute$0(LoggingExecutor.java:54) ~[dicoogle.jar:3.3.5]
        at java.lang.Thread.run(Thread.java:829) [?:?]

in ultrasound, shows ERROR IN DIMSE

**Comment by Enet4** [comment]
Sorry, but like in #575, we may not be able to diagnose the situation without more details, including a sample DICOM file and the steps needed to reproduce the problem.
